// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SerializationAddin
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSerializationAddinPackageString = "078d2513-90bc-4c7e-8d8c-2121fdf9ad2b";
        public static Guid guidSerializationAddinPackage = new Guid(guidSerializationAddinPackageString);

        public const string guidSerializationAddinPackageCmdSetString = "a14622ad-97e7-43b7-831a-8905f447b9c8";
        public static Guid guidSerializationAddinPackageCmdSet = new Guid(guidSerializationAddinPackageCmdSetString);

        public const string guidImagesString = "cb931358-c811-419f-812d-5a67e39535a7";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int GenerateMappingSerializationClassCodeId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}